import type { StageConfig } from '../types';
import { mk } from './helper';

export const stages00_05: StageConfig[] = [
  mk(0, {
    name: 'Семя',
    emoji: '🌰',
    description: 'Маленькое тёмно-коричневое семя лежит на земле. Видна лишь небольшая тень под ним. Кроны нет, ствола нет — только потенциал роста скрыт внутри.',
    trunkColor: '#8B6B4A',
    trunkColorDark: '#5A3A20',
    trunkHeight: 0,
    trunkBaseWidth: 0,
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0,
  }),
  mk(1, {
    name: 'Набухшее семя',
    emoji: '💧',
    description: 'Семя слегка увеличилось в размере, напитываясь влагой. Оболочка начала размягчаться, появляется едва заметный бугорок земли над ним.',
    trunkHeight: 0,
    trunkBaseWidth: 0,
    trunkColor: '#8B6B4A',
    trunkColorDark: '#5A3A20',
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    wrinkleCount: 0,
    bumpCount: 0,
  }),
  mk(2, {
    name: 'Проклюнувшееся семя',
    emoji: '🌱',
    description: 'Из семени показался крошечный белый корешок, уходящий в почву. Оболочка треснула, виден зелёный зачаток ростка.',
    trunkHeight: 0,
    trunkBaseWidth: 0,
    trunkColor: '#8B6B4A',
    trunkColorDark: '#5A3A20',
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    wrinkleCount: 0,
    bumpCount: 0,
  }),
  mk(3, {
    name: 'Корешок',
    emoji: '🌱',
    description: 'Корешок углубился в землю и разделился на два тонких усика. Росток приподнял семя над поверхностью почвы на пару миллиметров.',
    trunkColor: '#9E8C6A',
    trunkColorDark: '#6B4D2E',
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.06,
  }),
  mk(4, {
    name: 'Первый росток',
    emoji: '🌱',
    description: 'Из земли показался тонкий зеленовато-жёлтый стебелёк с двумя крошечными семядольными листочками на верхушке. Высота — несколько миллиметров.',
    trunkColor: '#9E8C6A',
    trunkColorDark: '#6B4D2E',
    rootCount: -1,
    branchCount: -1,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.08,
  }),
  mk(5, {
    name: 'Молодой росток',
    emoji: '🌿',
    description: 'Стебелёк окреп и приподнялся над землёй. Появился небольшой земляной холмик у основания. Видны две пары настоящих листьев, сочного светло-зелёного оттенка.',
    trunkColor: '#9E8C6A',
    trunkColorDark: '#6B4D2E',
    branchCount: -1,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.10,
  }),
];
