import type { StageConfig } from '../types';
import { mk } from './helper';

export const stages00_05: StageConfig[] = [
  mk(0, {
    name: 'Семя',
    emoji: '🌰',
    description: 'Маленькое тёмно-коричневое семя лежит на земле. Видна лишь небольшая тень под ним. Кроны нет, ствола нет — только потенциал роста скрыт внутри.',
    trunkColor: '#8B6B4A',
    trunkColorDark: '#5A3A20',
    trunkHeight: 0,
    trunkBaseWidth: 0,
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    viewZoom: 0.50,
    groundY: 0.88,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0,
  }),
  mk(1, {
    name: 'Набухшее семя',
    emoji: '💧',
    description: 'Семя слегка увеличилось в размере, напитываясь влагой. Оболочка начала размягчаться, появляется едва заметный бугорок земли над ним.',
    trunkHeight: 0,
    trunkBaseWidth: 0,
    trunkColor: '#8B6B4A',
    trunkColorDark: '#5A3A20',
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    viewZoom: 0.515,
    groundY: 0.881,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.02,
  }),
  mk(2, {
    name: 'Проклюнувшееся семя',
    emoji: '🌱',
    description: 'Из семени показался крошечный белый корешок, уходящий в почву. Оболочка треснула, виден зелёный зачаток ростка.',
    trunkHeight: 0,
    trunkBaseWidth: 0,
    trunkColor: '#8B6B4A',
    trunkColorDark: '#5A3A20',
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    viewZoom: 0.531,
    groundY: 0.882,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.04,
  }),
  mk(3, {
    name: 'Корешок',
    emoji: '🌱',
    description: 'Корешок углубился в землю и разделился на два тонких усика. Росток приподнял семя над поверхностью почвы на пару миллиметров.',
    trunkHeight: 0.008,
    trunkBaseWidth: 0.004,
    trunkColor: '#9E8C6A',
    trunkColorDark: '#6B4D2E',
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0,
    crownWidth: 0,
    canopyBackPuffs: 0,
    canopyFrontPuffs: 0,
    canopyPuffRadius: 0,
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    viewZoom: 0.546,
    groundY: 0.884,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.06,
  }),
  mk(4, {
    name: 'Первый росток',
    emoji: '🌱',
    description: 'Из земли показался тонкий зеленовато-жёлтый стебелёк с двумя крошечными семядольными листочками на верхушке. Высота — несколько миллиметров.',
    trunkHeight: 0.018,
    trunkBaseWidth: 0.006,
    trunkColor: '#9E8C6A',
    trunkColorDark: '#6B4D2E',
    rootCount: -1,
    branchCount: -1,
    crownHeight: 0.012,
    crownWidth: 0.01,
    canopyBackPuffs: 1,
    canopyFrontPuffs: 1,
    canopyPuffRadius: 0.01,
    canopyBackColor: { r: 60, g: 120, b: 70, a: 1 },
    canopyFrontColor: { r: 70, g: 135, b: 80, a: 1 },
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: false,
    viewZoom: 0.561,
    groundY: 0.885,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.08,
  }),
  mk(5, {
    name: 'Молодой росток',
    emoji: '🌿',
    description: 'Стебелёк окреп и приподнялся над землёй. Появился небольшой земляной холмик у основания. Видны две пары настоящих листьев, сочного светло-зелёного оттенка.',
    trunkHeight: 0.033,
    trunkBaseWidth: 0.008,
    trunkColor: '#9E8C6A',
    trunkColorDark: '#6B4D2E',
    branchCount: -1,
    crownHeight: 0.032,
    crownWidth: 0.023,
    canopyBackPuffs: 2,
    canopyFrontPuffs: 2,
    canopyPuffRadius: 0.012,
    canopyBackColor: { r: 55, g: 115, b: 68, a: 1 },
    canopyFrontColor: { r: 65, g: 130, b: 78, a: 1 },
    highlightCount: -1,
    flowerCount: -1,
    fruitCount: -1,
    sparkleCount: -1,
    particleCount: -1,
    glowOpacity: -1,
    grassCount: -1,
    mushroomCount: -1,
    hasMound: true,
    viewZoom: 0.577,
    groundY: 0.886,
    wrinkleCount: 0,
    bumpCount: 0,
    barkDetail: 0.10,
  }),
];
