import type { StageConfig } from '../types';
import { mk } from './helper';

export const stages28_31: StageConfig[] = [
  mk(28, {
    name: 'Цветущее дерево',
    emoji: '🌸',
    description: 'На дереве появляются первые цветы! Мелкие нежно-персиковые и абрикосовые бутоны усеивают верхнюю часть кроны. Один-два цветка пока заметны. Общий силуэт дерева не изменился, но настроение стало весенним.',
    trunkColor: '#915A2A',
    trunkColorDark: '#3C1F0A',
    barkColor: '#2F1E0E',
    branchCount: 6,
    flowerCount: 1,
    flowerColor: { r: 255, g: 200, b: 165, a: 0.78 },
    flowerColorAlt: { r: 255, g: 220, b: 185, a: 0.72 },
  }),
  mk(29, {
    name: 'Плодоносящее дерево',
    emoji: '🌸',
    description: 'Цветов становится больше — 3-4 нежных бутона рассыпаны по кроне, словно конфетти. Персиковые и тёпло-розовые оттенки создают красивый контраст с зелёной листвой.',
    flowerCount: 3,
    trunkColor: '#8E5828',
    trunkColorDark: '#391D08',
    barkColor: '#2C1C0C',
    branchCount: 6,
    flowerColor: { r: 255, g: 195, b: 155, a: 0.80 },
    flowerColorAlt: { r: 255, g: 215, b: 175, a: 0.74 },
  }),
  mk(30, {
    name: 'Пышное дерево',
    emoji: '🌸',
    description: 'Дерево в полном цвету! 5-6 цветков украшают крону. Из-под земли показались первые корни — два изогнутых коричневых усика на поверхности. У корней вырос первый крошечный гриб-сыроежка.',
    trunkColor: '#8E5828',
    trunkColorDark: '#391D08',
    barkColor: '#2C1C0C',
    branchCount: 6,
    flowerCount: 5,
    rootCount: 2,
    mushroomCount: 1,
    flowerColor: { r: 255, g: 190, b: 150, a: 0.82 },
    flowerColorAlt: { r: 255, g: 210, b: 170, a: 0.76 },
  }),
  mk(31, {
    name: 'Благоухающее дерево',
    emoji: '🌸',
    description: 'Цветение на пике. 7-8 крупных цветков с персиково-золотистым свечением рассыпаны по кроне. Корни изящно расходятся в стороны. Гриб у основания подрос, видна коричневая шляпка.',
    trunkColor: '#8B5525',
    trunkColorDark: '#361A06',
    barkColor: '#2A1A0A',
    branchCount: 6,
    flowerCount: 7,
    rootCount: 2,
    mushroomCount: 1,
    flowerColor: { r: 255, g: 185, b: 145, a: 0.84 },
    flowerColorAlt: { r: 255, g: 205, b: 165, a: 0.78 },
    flowerRadius: 2.8,
  }),
];
