import type { StageConfig } from '../types';
import { mk } from './helper';

export const stages32_35: StageConfig[] = [
  mk(32, {
    name: 'Великое дерево',
    emoji: '🌸',
    description: 'Цветы постепенно превращаются в первые плоды. Один-два крошечных красноватых яблочка видны в нижней части кроны. Цветов всё ещё много. Грибов у корней стало два.',
    trunkColor: '#8B5525',
    trunkColorDark: '#361A06',
    barkColor: '#2A1A0A',
    branchCount: 6,
    flowerCount: 8,
    fruitCount: 1,
    rootCount: 3,
    mushroomCount: 1,
    flowerColor: { r: 255, g: 185, b: 145, a: 0.84 },
    flowerColorAlt: { r: 255, g: 205, b: 165, a: 0.78 },
    fruitColor: { r: 225, g: 105, b: 85, a: 0.73 },
    fruitColorAlt: { r: 205, g: 90, b: 75, a: 0.68 },
  }),
  mk(33, {
    name: 'Старое дерево',
    emoji: '🌴',
    description: 'Плодов прибавилось — 3 красно-бордовых яблочка в глубине кроны. Цветение начинает спадать. Ствол потемнел до глубокого шоколадного оттенка с красноватым подтоном. Корни толще и длиннее.',
    trunkColor: '#885223',
    trunkColorDark: '#331808',
    barkColor: '#271808',
    branchCount: 6,
    flowerCount: 6,
    fruitCount: 3,
    rootCount: 3,
    mushroomCount: 2,
    fruitColor: { r: 220, g: 100, b: 80, a: 0.75 },
    fruitColorAlt: { r: 200, g: 85, b: 70, a: 0.70 },
  }),
  mk(34, {
    name: 'Мудрое дерево',
    emoji: '🌴',
    description: 'Дерево обретает характер. Плоды сочного яблочного цвета ярко выделяются на фоне листвы. Ствол покрыт глубокими морщинами и 3-4 наростами. Крона величественная, раскидистая.',
    trunkColor: '#885223',
    trunkColorDark: '#331808',
    barkColor: '#271808',
    branchCount: 7,
    flowerCount: 4,
    fruitCount: 4,
    rootCount: 3,
    mushroomCount: 2,
    bumpCount: 3,
    wrinkleCount: 7,
    swayAmount: 0.008,
    fruitColor: { r: 215, g: 95, b: 75, a: 0.76 },
    fruitColorAlt: { r: 195, g: 80, b: 65, a: 0.72 },
    fruitRadius: 2.1,
  }),
  mk(35, {
    name: 'Величественное дерево',
    emoji: '🌴',
    description: 'Финальная стадия плодоношения. 5-6 яблок насыщенного красно-рубинового цвета в кроне. Вокруг дерева появляется слабое тёплое свечение — аура зрелости. Корни расходятся на 3-4 усика.',
    trunkColor: '#855020',
    trunkColorDark: '#301606',
    barkColor: '#241606',
    branchCount: 7,
    flowerCount: 2,
    fruitCount: 6,
    rootCount: 4,
    mushroomCount: 2,
    bumpCount: 4,
    wrinkleCount: 7,
    glowOpacity: 0.08,
    glowColor: '#FFD7AA',
    fruitColor: { r: 210, g: 90, b: 70, a: 0.78 },
    fruitColorAlt: { r: 190, g: 75, b: 60, a: 0.74 },
    fruitRadius: 2.2,
  }),
];
