import type { StageConfig } from '../types';
import { mk } from './helper';

export const stages36_39: StageConfig[] = [
  mk(36, {
    name: 'Исполинское дерево',
    emoji: '🏛️',
    description: 'Дерево-исполин. Последние цветы опали, остались только плоды. Крона огромна — 50+ пучков листвы насыщенного изумрудного цвета. Ствол могучий, с 4 бугорками-наростами. Свечение усиливается.',
    trunkColor: '#855020',
    trunkColorDark: '#301606',
    barkColor: '#241606',
    branchCount: 7,
    flowerCount: 0,
    fruitCount: 5,
    rootCount: 4,
    glowOpacity: 0.10,
  }),
  mk(37, {
    name: 'Золотое дерево',
    emoji: '🏛️',
    description: 'Листва начинает приобретать тёплый золотистый отлив, словно в лучах закатного солнца. Блики на кроне стали ярче и многочисленнее. Вокруг дерева — мягкое янтарное свечение.',
    trunkColor: '#824E1E',
    trunkColorDark: '#2E1405',
    barkColor: '#221404',
    branchCount: 7,
    fruitCount: 4,
    rootCount: 4,
    glowOpacity: 0.13,
    canopyFrontColor: { r: 65, g: 120, b: 70, a: 1 },
    canopyBackColor: { r: 55, g: 105, b: 60, a: 1 },
    highlightColor: { r: 185, g: 215, b: 105, a: 0.48 },
    bumpCount: 5,
    wrinkleCount: 8,
  }),
  mk(38, {
    name: 'Священное дерево',
    emoji: '🏛️',
    description: 'Дерево источает внутренний свет. Золотисто-зелёная листва переливается оттенками от малахитового до янтарного. Плоды стали крупнее и словно светятся изнутри.',
    trunkColor: '#824E1E',
    trunkColorDark: '#2E1405',
    barkColor: '#221404',
    branchCount: 7,
    fruitCount: 3,
    rootCount: 4,
    glowOpacity: 0.16,
    canopyFrontColor: { r: 70, g: 125, b: 72, a: 1 },
    canopyBackColor: { r: 60, g: 108, b: 62, a: 1 },
    highlightColor: { r: 190, g: 220, b: 110, a: 0.50 },
    fruitColor: { r: 210, g: 95, b: 75, a: 0.80 },
    fruitColorAlt: { r: 195, g: 80, b: 65, a: 0.76 },
  }),
  mk(39, {
    name: 'Легендарное дерево',
    emoji: '🏛️',
    description: 'Дерево-легенда. Крона сияет золотисто-зелёными переливами. Плоды рубинового цвета стали редкостью — их всего 3. Свечение распространяется на всю площадь кроны. Корни мощные, словно змеи.',
    trunkColor: '#7F4C1C',
    trunkColorDark: '#2C1204',
    barkColor: '#201203',
    branchCount: 8,
    fruitCount: 3,
    rootCount: 5,
    glowOpacity: 0.19,
    canopyFrontColor: { r: 72, g: 128, b: 73, a: 1 },
    canopyBackColor: { r: 62, g: 110, b: 63, a: 1 },
    highlightColor: { r: 195, g: 225, b: 115, a: 0.52 },
    bumpCount: 5,
    wrinkleCount: 8,
  }),
];
