import type { StageConfig } from '../types';
import { mk } from './helper';

export const stages40_44: StageConfig[] = [
  mk(40, {
    name: 'Эпическое дерево',
    emoji: '🏛️',
    description: 'Дерево эпических масштабов. Вокруг кроны начинают парить первые светлячки — 6 крошечных золотистых частиц, медленно дрейфующих по орбитам. Свечение приобретает тёплый медовый оттенок.',
    trunkColor: '#7F4C1C',
    trunkColorDark: '#2C1204',
    barkColor: '#201203',
    branchCount: 8,
    fruitCount: 2,
    rootCount: 5,
    glowOpacity: 0.22,
    canopyFrontColor: { r: 75, g: 130, b: 72, a: 1 },
    canopyBackColor: { r: 65, g: 112, b: 62, a: 1 },
    highlightColor: { r: 200, g: 228, b: 118, a: 0.54 },
    bumpCount: 6,
    wrinkleCount: 9,
    particleCount: 6,
    particleColor: '#FFF0C8',
    swayAmount: 0.009,
  }),
  mk(41, {
    name: 'Мистическое дерево',
    emoji: '✨',
    description: 'Мистическое сияние окутывает дерево. Светлячков больше — 8-10, они танцуют в воздухе, оставляя лёгкий золотистый след. Листва приобретает изумрудно-золотой оттенок.',
    trunkColor: '#7C4A1A',
    trunkColorDark: '#2A1003',
    barkColor: '#1E1002',
    branchCount: 8,
    fruitCount: 1,
    rootCount: 5,
    glowOpacity: 0.25,
    glowColor: '#FFCC88',
    canopyFrontColor: { r: 78, g: 132, b: 71, a: 1 },
    canopyBackColor: { r: 68, g: 114, b: 61, a: 1 },
    highlightColor: { r: 205, g: 230, b: 120, a: 0.56 },
    bumpCount: 6,
    wrinkleCount: 9,
    particleCount: 8,
    particleColor: '#FFE8B0',
  }),
  mk(42, {
    name: 'Сияющее дерево',
    emoji: '✨',
    description: 'Дерево излучает чистый свет. 10-12 частиц парят широкими кругами. Крона переливается, словно усыпанная алмазной пылью. На плодах — капельки росы, отражающие свет.',
    trunkColor: '#7C4A1A',
    trunkColorDark: '#2A1003',
    barkColor: '#1E1002',
    branchCount: 8,
    fruitCount: 1,
    rootCount: 5,
    glowOpacity: 0.28,
    canopyFrontColor: { r: 80, g: 134, b: 70, a: 1 },
    canopyBackColor: { r: 70, g: 116, b: 60, a: 1 },
    highlightColor: { r: 208, g: 233, b: 122, a: 0.58 },
    bumpCount: 7,
    wrinkleCount: 10,
    particleCount: 10,
    particleColor: '#FFE0A0',
  }),
  mk(43, {
    name: 'Космическое дерево',
    emoji: '✨',
    description: 'Космическое древо. Первые золотые искорки появляются среди листвы — крошечные звёздочки, мерцающие тёплым золотом. 12+ светлячков парят по сложным орбитам. Аура охватывает всё дерево.',
    trunkColor: '#794818',
    trunkColorDark: '#280E02',
    barkColor: '#1C0E02',
    branchCount: 8,
    fruitCount: 0,
    rootCount: 6,
    glowOpacity: 0.31,
    canopyFrontColor: { r: 82, g: 136, b: 69, a: 1 },
    canopyBackColor: { r: 72, g: 118, b: 59, a: 1 },
    highlightColor: { r: 210, g: 235, b: 125, a: 0.60 },
    bumpCount: 7,
    wrinkleCount: 10,
    particleCount: 12,
    particleColor: '#FFD890',
    sparkleCount: 5,
    sparkleColor: '#F5C542',
    sparkleRadius: 2.2,
  }),
  mk(44, {
    name: 'Звёздное дерево',
    emoji: '✨',
    description: 'Звёздное дерево сияет в ночи. Искорки-звёздочки рассыпаны по всей кроне (6-7 штук), каждая с едва заметным крестообразным сиянием. Светлячки (14+) образуют созвездия вокруг ветвей.',
    trunkColor: '#794818',
    trunkColorDark: '#280E02',
    barkColor: '#1C0E02',
    branchCount: 9,
    fruitCount: 0,
    rootCount: 6,
    glowOpacity: 0.34,
    canopyFrontColor: { r: 84, g: 138, b: 68, a: 1 },
    canopyBackColor: { r: 74, g: 120, b: 58, a: 1 },
    highlightColor: { r: 212, g: 238, b: 128, a: 0.62 },
    bumpCount: 8,
    wrinkleCount: 10,
    particleCount: 14,
    particleColor: '#FFD080',
    sparkleCount: 7,
    sparkleColor: '#F5C542',
    sparkleRadius: 2.4,
    swayAmount: 0.010,
  }),
];
