import type { StageConfig } from '../types';
import { mk } from './helper';

export const stages45_49: StageConfig[] = [
  mk(45, {
    name: 'Древо жизни',
    emoji: '🌟',
    description: 'Древо жизни — воплощение витальности. Золотисто-изумрудная крона пульсирует энергией. 16 светлячков водят хороводы, 7 искр-звёздочек мерцают в глубине листвы. Аура тёплого света охватывает всё.',
    trunkColor: '#764616',
    trunkColorDark: '#260C01',
    barkColor: '#1A0C01',
    branchCount: 9,
    rootCount: 6,
    glowOpacity: 0.37,
    canopyFrontColor: { r: 86, g: 140, b: 67, a: 1 },
    canopyBackColor: { r: 76, g: 122, b: 57, a: 1 },
    highlightColor: { r: 215, g: 240, b: 130, a: 0.64 },
    bumpCount: 8,
    wrinkleCount: 11,
    particleCount: 16,
    particleColor: '#FFC870',
    sparkleCount: 8,
    sparkleColor: '#F5C542',
    sparkleRadius: 2.6,
    grassCount: 7,
    mushroomCount: 3,
    swayAmount: 0.010,
  }),
  mk(46, {
    name: 'Древо познания',
    emoji: '🌟',
    description: 'Древо познания источает мудрость. Крона — симфония изумрудного, золотого и янтарного. Искры стали ярче и крупнее (9+). Светлячки — 18 штук — двигаются по замысловатым траекториям.',
    trunkColor: '#764616',
    trunkColorDark: '#260C01',
    barkColor: '#1A0C01',
    branchCount: 9,
    rootCount: 6,
    glowOpacity: 0.40,
    glowColor: '#FFC070',
    canopyFrontColor: { r: 88, g: 142, b: 66, a: 1 },
    canopyBackColor: { r: 78, g: 124, b: 56, a: 1 },
    highlightColor: { r: 218, g: 242, b: 132, a: 0.66 },
    bumpCount: 9,
    wrinkleCount: 11,
    particleCount: 18,
    particleColor: '#FFC060',
    sparkleCount: 9,
    sparkleColor: '#F5C542',
    sparkleRadius: 2.7,
    grassCount: 8,
    mushroomCount: 3,
  }),
  mk(47, {
    name: 'Древо мудрости',
    emoji: '🌟',
    description: 'Древо мудрости — пик земного величия. Крона переливается всеми оттенками жизни. 10 искр сверкают подобно бриллиантам. 20 светлячков исполняют танец вечности. Корни подобны змеям.',
    trunkColor: '#734414',
    trunkColorDark: '#240A01',
    barkColor: '#180A01',
    branchCount: 9,
    rootCount: 7,
    glowOpacity: 0.43,
    canopyFrontColor: { r: 90, g: 144, b: 65, a: 1 },
    canopyBackColor: { r: 80, g: 126, b: 55, a: 1 },
    highlightColor: { r: 220, g: 244, b: 134, a: 0.68 },
    bumpCount: 9,
    wrinkleCount: 12,
    particleCount: 20,
    particleColor: '#FFB850',
    sparkleCount: 10,
    sparkleColor: '#F5C542',
    sparkleRadius: 2.9,
    grassCount: 9,
    mushroomCount: 3,
    swayAmount: 0.011,
  }),
  mk(48, {
    name: 'Древо вечности',
    emoji: '🌟',
    description: 'Древо вечности превосходит время. Божественное сияние исходит от каждой ветви и листа. 11 ослепительных искр пульсируют в такт дыханию вселенной. 22 светлячка — духи предков.',
    trunkColor: '#734414',
    trunkColorDark: '#240A01',
    barkColor: '#180A01',
    branchCount: 10,
    rootCount: 7,
    glowOpacity: 0.46,
    canopyFrontColor: { r: 92, g: 146, b: 64, a: 1 },
    canopyBackColor: { r: 82, g: 128, b: 54, a: 1 },
    highlightColor: { r: 222, g: 246, b: 136, a: 0.70 },
    bumpCount: 10,
    wrinkleCount: 12,
    particleCount: 22,
    particleColor: '#FFB040',
    sparkleCount: 11,
    sparkleColor: '#F5C542',
    sparkleRadius: 3.1,
    grassCount: 10,
    mushroomCount: 4,
  }),
  mk(49, {
    name: 'Древо мироздания',
    emoji: '🌟',
    description: 'Древо мироздания — абсолютная гармония и совершенство. Крона сияет космическим светом: изумрудные, золотые и янтарные переливы сливаются в единую симфонию. 12 ослепительных искр-звёзд пульсируют в кроне. 24 светлячка парят величественным хороводом. Могучий ствол цвета тёмного шоколада с глубокими морщинами и наростами. Корни расходятся на 7 змеевидных усиков. Четыре гриба у подножия завершают картину. Аура тёплого солнечного света простирается далеко за пределы кроны. Это не просто дерево — это центр мироздания.',
    trunkColor: '#704212',
    trunkColorDark: '#220801',
    barkColor: '#160801',
    branchCount: 10,
    rootCount: 7,
    glowOpacity: 0.50,
    glowColor: '#FFB060',
    canopyFrontColor: { r: 95, g: 148, b: 63, a: 1 },
    canopyBackColor: { r: 84, g: 130, b: 53, a: 1 },
    highlightColor: { r: 225, g: 248, b: 138, a: 0.72 },
    bumpCount: 10,
    wrinkleCount: 13,
    particleCount: 24,
    particleColor: '#FFA830',
    sparkleCount: 12,
    sparkleColor: '#F5C542',
    sparkleRadius: 3.3,
    grassCount: 10,
    mushroomCount: 4,
    swayAmount: 0.012,
    viewZoom: 1.25,
  }),
];
